dist: xenial
sudo: required
language: python
python: 3.6
before_script:
- git lfs pull
install:
- pip install --upgrade pip setuptools wheel
- pip install -r requirements.txt
script:
- pytest --cov rulm
after_success:
- codecov
deploy:
  provider: pypi
  user: Phoenix120
  password:
    secure: ueaFMBiVlNSPmwivJ0uMGJw1ntj6nTuCqIuxYw0IXQDUebPkU6QZLH3o8k59BgD1o5+7yXmpWQHXb7B5UYr0pBC/4wEutatoGLzDmcTv1DaYn7kzrv5PTBSQVEvCQNzA8jNog0j6Ljg9Z7CN3H/vGIIdPRt1Gxmu0dPCrX3rGMlwKZLH5/gRaZlbgxtov/UGfIUEOgJmM1eJvZYS8Y5InmxlUBJmT0U1QDe1cBooax43KlspQzCJSJ6NciMGXSZUi5nPSb9sKbqvbOjRnCydcazeQwoRf14qIwFS3b7nL4TLb+rRSHFKuOJ9cmnAF+f5qo0ytJuYZqo3dNS8LqwuJH0tXyO4fo5T7Xe2k7eIfla4mg1T+uss5zIM0ttfW/ApKQanAr2kZ/tMl6ywWkWLJ1crSYM9RjUewZw8Z1qwYbEDJrcWIBZxkyPfEkzilgjAvlf4rmEUR3eJtm2YBgoz5XiNR2sdTeRFUgAcZUyC7nx+N15FJgw1HTtZeqbedPGgq84sMk31OxGfpGDJQ9iHqHavvTdxiRjA8YLNlxAeZ+Upop6zLznUM7iE742tNAjqjaXhGR6128Viggn4hL2PZuFYlmRx5Rt7LhCr1OgKViodNJwyoWZTFDl3p+b6GoJai9FPIewX6nmfQTAeYweFM8yz38akC8v21P3/kNeJ2/w=
  on:
    branch: master
    tags: true
