dist: trusty
sudo: required
language: python
python: 3.6
before_install:
- sudo apt-get install git-lfs
- sudo git lfs install
before_script:
- git lfs pull
install:
- pip install --upgrade pip setuptools wheel
- pip install -r requirements.txt &> install.log
script: pytest
